### ISSUE TITLE
plus de lien sur Arkena

### ISSUE THREAD

**Issue by yolateng0** [sfab07/bookmarks.xml-Radiotray-Lite#1]
Beaucoup de radios ont changé leur url de stream.
arkena.com tout ces ne fonctionnent lus

**Comment by sfab07** [comment]
J'ai réalisé une grosse mise à jour (seul chante france et mfm sont à revoir). Si toutefois la version avec radiotray selector vous intéresse je peux éventuellement la remettre.

**Comment by yolateng0** [comment]
j ai mis a jour de mon côté les liens à jour aussi :-)
